### ISSUE TITLE
Link to slides for week 2

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#10]
Hey,

I just found that the link to slides accidentally has 'winter' in it, but replacing that with 'spring' works.

http://uchicago.cloud/sessions/session2/MPCS51033-2017-Spring-Lecture2.pdf

**Comment by tabinks** [comment]
Thanks.  I'll fix it on my end.

**Comment by tabinks** [comment]
Done.
