### ISSUE TITLE
Office Hours - Sundays 4-6pm

### ISSUE THREAD

**Issue by susanstevens** [uchicago-cloud/mpcs51033-2017-spring-forum#12]
My office hours will be on Sundays from 4-6pm starting this weekend! We'll most likely be in Young, and I'll post the exact room as soon as I find out what's available.

**Comment by susanstevens** [comment]
We'll be in Young 302!

**Comment by taburaad** [comment]
Hi @susanstevens ,

Would it be possible to hold office hours Saturdays at ~noon instead? (Thats when machine learning OH end, also in Young.) I know thats much easier to make for Umar and I, but I can't speak for the rest of the class and was wondering if that works with your schedule.

Tony

**Comment by susanstevens** [comment]
Hmm... I _might_ be able to do that some weeks. I still need to do office hours on Sunday this weekend. I'll post to the forum if there's a week that I'm able to do Saturday at noon instead.

**Comment by taburaad** [comment]
Ok, no problem at all, see you tomorrow. Thanks
