### ISSUE TITLE
Python PIL Library Error

### ISSUE THREAD

**Issue by imweihuang** [uchicago-cloud/mpcs51033-2017-spring-forum#13]
Hello, 

Does anyone get below error while posting image to localhost using 'curl' from command line?
`RuntimeError: NotImplementedError('Unable to find the Python PIL library.  Please view the SDK documentation for details about installing PIL on your system.',)`

I tried to install PIL and Pillow by following some instructions on stackoverflow, but I'm still getting the same error again. If I rerun the application, I get following error
`RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL`

I was able to go back to the first error by uninstall PIL library.

**Comment by ijl0322** [comment]
DId you try installing only Pillow and not PIL ? 
I think the two are not compatible with each other. I was able to fix this by uninstalling PIL and re-installing Pillow. I had to do restart my terminal after installation though..

**Comment by imweihuang** [comment]
@ijl0322 I just reinstalled the Pillow and restart the terminal and it works. Thanks for the help!
