### ISSUE TITLE
Not writing to database fast enough?

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#19]
When I post a picture as a new user, a new User object is posted, along with its associated picture. When get_data() is called in the UserHandler, it queries for this new user to find the key(s) of that user's pix. This query returns None because it can't find that user, but if I sleep for 1 second before that query, it finds it without a problem. Is it not writing the User fast enough? Is there something I can do to wait to make sure its written before querying?

Thanks

**Comment by tabinks** [comment]
Take a look at this:
https://cloud.google.com/appengine/docs/standard/python/ndb/transactions

If you wrap your code in @ndb.transactional you can guarantee that it will complete before moving on.  Although, I think the behavior you are seeing is odd.  It doesn't seem that it would take that long to write.
