### ISSUE TITLE
post from iOS not succeeding

### ISSUE THREAD

**Issue by uykhokhar** [uchicago-cloud/mpcs51033-2017-spring-forum#21]
i'm able to post json to the backend dev server using curl, but the post are not succeeding from iOS. In iOS i get nil response and nil data. I'm using the code provided. 

(I've configured the info p-list to send the data to localhost:8080 without ssl).

**Comment by susanstevens** [comment]
Were you able to get this working? My first question would be, did you start you server before attempting to post from your iOS app?
