### ISSUE TITLE
Definitive Turn in Date for Assignment 2

### ISSUE THREAD

**Issue by tabinks** [uchicago-cloud/mpcs51033-2017-spring-forum#24]
I know that everyone is working diligently on their App Engine Backend and for some its taking longer than they expected.  I think this is a very important assignment, but I want to make sure that we are progressing through the material and keeping our focus on the new technologies we will be covering.

So, please have *Assignment 2 turned in by 11:59PM on Sunday, April 23rd*.  This will give those who need one more office hours session.  After this, I want you to concentrate on Firebase.

We will grade Assignment 2 and provide some (hopefully) valuable feedback.  Once you get it returned, you will be allowed to resubmit Assignment 2 by Week 9.  The remaining homework schedule will remain the same.

**Comment by susanstevens** [comment]
Hi @tabinks. I had a question come up in office hours that I'm sure others are wondering too! Will the grade for Assignment 2 be an average of the initial grade and the resubmission grade? Or does the grade for the resubmission cancel out the previous grade?

Thanks!

**Comment by tabinks** [comment]
We'll average it out.
