### ISSUE TITLE
Tutorial 1: Registering users

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#27]
Has anyone successfully registered a user in the first Ray W tutorial? I am doing exactly as they say but no user is created, nor is any error message printed. Some people said they solved the issue by re-pasting the API_KEY in the Google plist, but that hasn't worked either.

Thanks

**Comment by imweihuang** [comment]
Have you tried registering an user with a long password? I had the same issue and figured that the user is created only when the password given is more than 5 characters.

**Comment by tabinks** [comment]
@taburaad I remember seeing something about the API key being missing for some other services.  
@imweihuang That seems odd.  Check the rules config on the database to see if there is a limit set.

Either way, for the chat app we are building, we are going to be using Google authentication.

**Comment by taburaad** [comment]
Ok, cool. And Wei you were right, needs to be at least 6 chars, thanks
