### ISSUE TITLE
Firebase cloud functions availability for free accounts ? 

### ISSUE THREAD

**Issue by ijl0322** [uchicago-cloud/mpcs51033-2017-spring-forum#32]
Hi, 

I tried using firebase's cloud function to set up sending out emails to the user. 
I followed firebase's tutorial and example code here: https://github.com/firebase/functions-samples/blob/master/quickstarts/email-users/functions/index.js#L40-L43
to implement the function and had no problem deploying or triggering it when a new user is authenticated, but I'm getting this error on the log: 

Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions

Is this a limitation for free accounts ? If so, can we just push the function to github rather than having a working version of it on the server side ? Thanks.

**Comment by tabinks** [comment]
You do need to have billing enabled, but there is free quota of 2M/month.

If you do not want to enable billing, you can just commit your code.  Make
sure to comment everything out properly so that the rest of the application
works.
