### ISSUE TITLE
Dynamic Link "Open Link in App" page

### ISSUE THREAD

**Issue by naietsg** [uchicago-cloud/mpcs51033-2017-spring-forum#33]
Did anyone by any chance run into this error? The dynamic link page links to the image below instead of directly opening the application. I'm pretty sure it's something trivial, but I've been working on it for awhile and have not been able to figure out what it might be. Thanks!

![dynamiclink](https://cloud.githubusercontent.com/assets/8528766/25720051/19d0b37c-30d1-11e7-8126-d83abf83885e.png)

**Comment by ijl0322** [comment]
I think it's just apple making sure that the user knows where they're going. This also shows up when Im trying to open facebook or some other apps dynamic link. For me this wouldn't show up when I'm clicking from my notes, by will show up when I'm trying to open the link from iMessages or line. Not sure if it's an issue that needs to be solved ?

**Comment by naietsg** [comment]
I was under the assumption that the link should open straight to the app from iMessage/Email (as it does in the Firechat2 playground)

edit: still interested in this for the final project.

**Comment by tabinks** [comment]
@aietsg Did you try it from Notes to see if it was any different?

**Comment by naietsg** [comment]
yeah I unfortunately get the same behavior in Notes.
