### ISSUE TITLE
Completion blocks in Firebase observe listeners

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#35]
Hey everyone,

How do you deal with completion blocks in firebase observe listeners? When you have something like

1. Observe and save values xyz
2. Load values xyz in a table

How do you ensure that the table is loaded only after those values are loaded? Because its asynchronous, my pages sometimes load before the values are saved, thus resulting in nils. Some implementation of a completion block is what I think I am looking for but I'm shaky on those.

Tony

**Comment by taburaad** [comment]
Another specific problem stemming from this:

I have 2 or 3 nested observe statements, and in the innermost one I am trying to save to a class variable. However, once I go 2-3 levels in, I cannot write/save to class variables anymore - its like they're unreachable from that depth.

**Comment by susanstevens** [comment]
You can call `tableView.reloadData()` inside the completion block to make sure it loads once you have data. 

Here's an example:

```
reference.observe(.value, with { snapshot in
    var freshData = [MessageItem]()
    for item in snapshot.children {
        let messageItem = MessageItem(snapshot: item as! FIRDataShapshot)
        freshData.append(messageItem)
    }
    self.messages = freshData
    self.tableView.reloadData()
})
```

I'm not sure why you're having trouble writing to variables inside a closure. Make sure you're using `self.myVariable` instead of just `myVariable`.

**Comment by taburaad** [comment]
Cool, thanks. Its only because they're nested, but I'm getting around it by using setters.
