### ISSUE TITLE
Getting started with Assignment 4

### ISSUE THREAD

**Issue by naietsg** [uchicago-cloud/mpcs51033-2017-spring-forum#39]
1. @tabinks would you mind posting the write up (if I am not missing it)?

2. Has anyone happened to come across the following error: 

<img width="648" alt="cloudkit" src="https://cloud.githubusercontent.com/assets/8528766/26017417/0f677114-372f-11e7-969f-9fa50160dcf0.png">

There are a bunch of SO/Apple threads about this (the picture is from [here](https://stackoverflow.com/questions/40596802/xcode-8-your-account-does-not-have-sufficient-permissions-to-modify-containers)). The CloudKit dashboard says that I need to "assign an App ID to a CloudKit Container in Xcode", but iCloud is not available as a capability in xCode (where all of the advanced capabilities are unavailable). I've tried manually setting the provisioning profiles, following the steps to update capabilities, and downgrading/upgrading my version of Xcode.

**Comment by susanstevens** [comment]
Are you using a paid developer account? I believe you'll need one to use CloudKit. Once you upgrade to a paid account, you should see all the options you need appear in Xcode. (If you don't, try quitting Xcode and reopening it.)
