### ISSUE TITLE
Getting Python helper script to work

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#46]
I'm using the keyID of a server-to-server key I made, which has the public key saved in it. In pycloudkit.py I've replaced this line as well as my project name, and my private key is saved in the same directory as my script. When I run 'python pycloudkit.py', I ultimately get this error: `urllib2.HTTPError: HTTP Error 503: Service Unavailable.` This is what prints out before the error:

`Print out all the zones (we are just using default.)
Requesting list of zones...
URL:  https://api.apple-cloudkit.com/database/1/iCloud.cloud.UChicago.cloud.LOLOL/development/public/zones/list
Data:
Headers:  {'X-Apple-CloudKit-Request-ISO8601Date': '2017-05-19T04:25:30Z', 'X-Apple-CloudKit-Request-SignatureV1': u'MEYCIQDUjcbQ530AgEI8AsRemTXBQ37rZ8rYuGu7mWd1lEOILQIhAL0MzXBjQ9f/ciCEUO1si0FbKa4qXE3kf3csfptuzHcM', 'X-Apple-CloudKit-Request-KeyID': 'this_is_my_keyID'}
Params:  None`

Also, going to this url results in 'no auth method found' or 'Authentication failed, please check you have the correct API Token for this container' if I try to add the token on the end. 

https://api.apple-cloudkit.com/database/1/iCloud.cloud.UChicago.cloud.LOLOL/development/public/records/query/

**Comment by tabinks** [comment]
We figured it out....it was one of the most frustrating bugs ever....typo 😋.

**Comment by naietsg** [comment]
@taburaad or @tabinks do you by any chance remember what the typo was -- running into a similar issue with nearly identical headers and hoping maybe there's a similar cause

edit: it appears to be working now even though I haven't changed anything. Will come back in a little bit to verify.

edit 2: still working -- don't know what happened. Gonna give a few more hours, but if I don't update this, sorry for the mentions.
