### ISSUE TITLE
Submitting to Assignment 1 Repositories

### ISSUE THREAD

**Issue by susanstevens** [uchicago-cloud/mpcs51033-2017-spring-forum#5]
Hi @tabinks -- It looks like each tutorial creates a new repository. Does everyone need to clone local copies of the tutorial repositories and copy everything into their Assignment 1 repo for the class? What's the best way to do that?

**Comment by tabinks** [comment]
Hi.  You should be typing the tutorials out and using the example as a reference.  The repo should just be you own code.  Also, please include the URL to the appspot hosted project.

**Comment by tabinks** [comment]
Put the URL in the README file
