### ISSUE TITLE
Multiprocessing Python lib on app engine

### ISSUE THREAD

**Issue by taburaad** [uchicago-cloud/mpcs51033-2017-spring-forum#62]
I'm using the app engine standard environment, which runs pure Python 2.7 with "no C code". So, when I try running Multiprocessing on it, it fails because some of that library is written in C. Is there any way around this, or would I need to 1.) use the flexible environment or 2.) find a way around using multiprocessing?

Thanks

**Comment by taburaad** [comment]
Nevermind - I found that removing multiprocessing code worked best for now.

**Comment by tabinks** [comment]
I don't think you can in standard environment.   One alternative would be
to use the task queue to do multiprocessing. You can break up your job into
a bunch of smaller tasks and submit to the task queue.

In practice, I bet this would be very expensive to do.
