### ISSUE TITLE
Guestbook tutorial - 404 Not Found

### ISSUE THREAD

**Issue by imweihuang** [uchicago-cloud/mpcs51033-2017-spring-forum#7]
Hello, 

Per the [Guestbook tutorial link](https://cloud.google.com/appengine/docs/standard/python/tutorials) provided, only the first part (Guestbook introduction and setup) of the tutorial is working, the rest are showing 404 Error. Is this expected? Do we only need to complete the first part?
<img width="776" alt="screen shot 2017-04-04 at 10 15 10 pm" src="https://cloud.githubusercontent.com/assets/24487707/24688266/8088b9f2-1984-11e7-8201-dceaf27a8d46.png">

**Comment by tabinks** [comment]
That's odd.  It works for me.

Yes, you should be doing the entire thing.  I would just wait and check back.

**Comment by imweihuang** [comment]
It works for me now, I figured I should just continue from the first part instead of go to other parts directly. Thanks!
